### PR TITLE
(maint) Adding snyk testing workflow

### PR DESCRIPTION
**Pull request by abottchen**

### CODE REVIEW

**Comment by abottchen** [comment]
Setting this as a draft for the moment while waiting for the key to be added.

**Comment by abottchen** [comment]
The FOSS key has been added.

**Review by MikaelSmith — APPROVED** [review]
This looks fine as long as it's following our recommendations for public repos.

**Comment by abottchen** [comment]
@LivingInSyn Just double checking, but I believe this is in line with our recommendations for public repos.  Figured I'd loop you in to make sure.

**Review by LivingInSyn — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
